Name:           orthogonals
# Version comes from the Makefile: make rpm passes --define "pkgver X.Y.Z".
Version:        %{pkgver}
Release:        1%{?dist}
Summary:        Command-line tool that turns a Linux desktop into a virtual machine host with native GPU passthrough — run Windows or other guest operating systems in a VM with a real, dedicated GPU at near-native performance.
License:        GPL-3.0-only
URL:            https://github.com/stronautt/orthogonals
Source0:        %{name}-%{version}.tar.gz
# Intel iGPU + NVIDIA dGPU hosts only
ExclusiveArch:  x86_64
BuildRequires:  golang

# virtualization stack
Requires:       qemu-kvm
Requires:       libvirt
Requires:       edk2-ovmf
Requires:       swtpm-tools
# host configuration binaries the apply steps invoke
Requires:       dracut
Requires:       policycoreutils
Requires:       policycoreutils-python-utils
Requires:       libnotify
# dGPU launch UX: GNOME's "Launch using Discrete Graphics Card"
Requires:       switcheroo-control
# version comes from the Makefile (artifacts.LookingGlassVersion); must match the host
Requires:       looking-glass-client = %{lgver}

%description
Same machine, orthogonal axes: Windows at full GPU speed, Linux never pauses.

%prep
%autosetup

%build
CGO_ENABLED=0 go build -ldflags "-X github.com/stronautt/orthogonals/internal/cli.Version=%{version}" -o orthogonals .

%install
install -Dm0755 orthogonals %{buildroot}%{_bindir}/orthogonals
# shell completions generated by the just-built binary (cobra)
install -d %{buildroot}%{_datadir}/bash-completion/completions
./orthogonals completion bash > %{buildroot}%{_datadir}/bash-completion/completions/orthogonals
install -d %{buildroot}%{_datadir}/zsh/site-functions
./orthogonals completion zsh > %{buildroot}%{_datadir}/zsh/site-functions/_orthogonals
install -d %{buildroot}%{_datadir}/fish/vendor_completions.d
./orthogonals completion fish > %{buildroot}%{_datadir}/fish/vendor_completions.d/orthogonals.fish

%files
%license LICENSE
%doc README.md
%{_bindir}/orthogonals
%{_datadir}/bash-completion/completions/orthogonals
%{_datadir}/zsh/site-functions/_orthogonals
%{_datadir}/fish/vendor_completions.d/orthogonals.fish
