Name:           orthogonals
# Version comes from the Makefile: make rpm passes --define "pkgver X.Y.Z".
Version:        %{pkgver}
Release:        1%{?dist}
Summary:        Turn a Linux desktop into a GPU-passthrough virtual machine host
License:        GPL-3.0-only
URL:            https://github.com/stronautt/orthogonals
Source0:        %{name}-%{version}.tar.gz
# Intel iGPU + NVIDIA dGPU hosts only
ExclusiveArch:  x86_64
BuildRequires:  golang

# virtualization stack
Requires:       qemu-kvm
Requires:       libvirt
Requires:       edk2-ovmf
Requires:       swtpm-tools
# host configuration binaries the apply steps invoke
Requires:       dracut
Requires:       policycoreutils
Requires:       policycoreutils-python-utils
# the hook runtime execs notify-send for desktop notifications
Requires:       /usr/bin/notify-send
# dGPU launch UX: GNOME's "Launch using Discrete Graphics Card"
Requires:       switcheroo-control
# version comes from the Makefile (artifacts.LookingGlassVersion); must match the host
Requires:       looking-glass-client = %{lgver}

%description
Same machine, orthogonal axes: Windows at full GPU speed, Linux never pauses.

orthogonals turns a Fedora desktop with an Intel iGPU and one NVIDIA dGPU
into a Looking Glass Windows 11 VM host: it detects the hardware topology,
runs preflight checks, applies the VFIO host configuration, defines and
installs the guest, and verifies the result — with every host mutation
journaled so undo restores the machine byte-identically.

%prep
%autosetup

%build
CGO_ENABLED=0 go build -ldflags "-X github.com/stronautt/orthogonals/internal/cli.Version=%{version}" -o orthogonals .

%install
install -Dm0755 orthogonals %{buildroot}%{_bindir}/orthogonals
# shell completions generated by the just-built binary (cobra)
install -d %{buildroot}%{_datadir}/bash-completion/completions
./orthogonals completion bash > %{buildroot}%{_datadir}/bash-completion/completions/orthogonals
install -d %{buildroot}%{_datadir}/zsh/site-functions
./orthogonals completion zsh > %{buildroot}%{_datadir}/zsh/site-functions/_orthogonals
install -d %{buildroot}%{_datadir}/fish/vendor_completions.d
./orthogonals completion fish > %{buildroot}%{_datadir}/fish/vendor_completions.d/orthogonals.fish

%files
%license LICENSE
%doc README.md
%{_bindir}/orthogonals
%{_datadir}/bash-completion/completions/orthogonals
%{_datadir}/zsh/site-functions/_orthogonals
%{_datadir}/fish/vendor_completions.d/orthogonals.fish

# Versions come from git tags; per-release history lives in the GitHub
# release notes, not here.
%changelog
* Thu Jul 23 2026 Pavlo Hrytsenko <pashagricenko@gmail.com> - %{pkgver}-1
- Built from the release tag; see the GitHub release notes for changes.
